// Single source of truth for the acceptance contract, the interpretation
// register, the assumption ledger and the transition map of the
// Yang–Mills specification. `node build.mjs` validates this file and
// generates the LaTeX tables in generated/ plus ledger.json.
//
// Strings are LaTeX (String.raw keeps backslashes). Never write a dollar
// sign directly followed by an opening brace: inside a template literal that
// starts an interpolation.

const r = String.raw;

export const revision = {
  version: '1.3',
  date: '2026-09-25',
};

// S1/S2 are normative; S3/S4 fix the minimum axiomatic strength.
export const sources = [
  {
    id: 'S1',
    title: 'A. Jaffe, E. Witten, Quantum Yang–Mills Theory (official problem description)',
    url: 'https://www.claymath.org/wp-content/uploads/2022/06/yangmills.pdf',
    sha256: '3558403ca14c11e382f73a09e548222708540bfdf478cf96aa11c52d43e23e09',
    bytes: 195976,
    retrieved: '2026-09-24',
  },
  {
    id: 'S2',
    title: 'Clay Mathematics Institute, Millennium Prize Description and Rules (adopted 2018-09-26)',
    url: 'https://www.claymath.org/wp-content/uploads/2022/03/millennium_prize_rules_0.pdf',
    sha256: '9b5003745c0ae7268dc7769f83e1c61eaca674f28631f1df2cd8400976640b2a',
    bytes: 43263,
    retrieved: '2026-09-24',
  },
  {
    id: 'S3',
    title: 'R. F. Streater, A. S. Wightman, PCT, Spin and Statistics, and All That (1964) — reference [45] of S1',
  },
  {
    id: 'S4',
    title: 'K. Osterwalder, R. Schrader, CMP 31 (1973) 83–112 and CMP 42 (1975) 281–305 — reference [35] of S1',
  },
];

// class: NORMATIVE (mathematical content of S1), PROCEDURAL (S2),
// DERIVED (logically implied by normative items), GOVERNANCE (recommended).
export const requirements = [
  { id: 'YM-01', title: 'Target object', cls: 'NORMATIVE', anchor: r`S1 \S3--4`,
    text: r`For each admissible $G$ a quantum field theory $\mathcal T_G=(\mathcal H,U,\Omega,\mathcal D,\{\mathcal O_i\}_{i\in I})$ on Minkowski space $\mathbb R^{1,3}$ in the sense of Definition~\ref{def:wightman}.` },
  { id: 'YM-02', title: 'All gauge groups', cls: 'NORMATIVE', anchor: r`S1 \S4`, interp: ['I-2'],
    text: r`The statement holds for \emph{every} compact simple gauge group. Constants (including $\Delta$) may depend on $G$; uniformity in $G$ is \emph{not} required.` },
  { id: 'YM-03', title: r`Space-time $\mathbb R^4$`, cls: 'NORMATIVE', anchor: r`S1 \S4, \S6`,
    text: r`The theory lives on $\mathbb R^4$: not on a lattice, not on a torus $T^4$, not in dimension $d<4$, and without any remaining UV or IR cut-off.` },
  { id: 'YM-04', title: 'Non-triviality', cls: 'NORMATIVE', anchor: r`S1 \S4`, interp: ['I-1'],
    text: r`$\mathcal T_G$ is non-trivial. The term is not defined in S1; working definition in \ref{I-1}.` },
  { id: 'YM-05', title: 'Hilbert space and symmetry', cls: 'NORMATIVE', anchor: r`S1 \S3; S3`,
    text: r`A separable Hilbert space $\mathcal H$ with a strongly continuous unitary representation $U$ of the restricted Poincar\'e group $\mathcal P_+^\uparrow$ (or its covering group).` },
  { id: 'YM-06', title: 'Spectrum condition', cls: 'NORMATIVE', anchor: r`S1 \S3--4`,
    text: r`The joint spectrum of the generators $(H,\vec P)$ lies in the closed forward cone $\overline V_+$; in particular $H\ge 0$.` },
  { id: 'YM-07', title: 'Vacuum', cls: 'NORMATIVE', anchor: r`S1 \S3`,
    text: r`A Poincar\'e-invariant vector $\Omega\in\mathcal H$, unique up to a phase.` },
  { id: 'YM-08', title: 'Local fields', cls: 'NORMATIVE', anchor: r`S1 \S3; S3`,
    text: r`Operator-valued tempered distributions $\mathcal O_i$ on a common dense $U$-invariant domain $\mathcal D\ni\Omega$, Poincar\'e-covariant, with $\Omega$ cyclic for the polynomial field algebra.` },
  { id: 'YM-09', title: 'Locality', cls: 'NORMATIVE', anchor: r`S1 \S3`,
    text: r`$[\mathcal O_i(f),\mathcal O_j(g)]=0$ on $\mathcal D$ whenever $\operatorname{supp}f$ and $\operatorname{supp}g$ are space-like separated.` },
  { id: 'YM-10', title: 'Field content', cls: 'NORMATIVE', anchor: r`S1 \S4 and fn.~1`,
    text: r`Local fields correspond to gauge-invariant local polynomials in $F$ and its covariant derivatives (e.g.\ $\operatorname{Tr}F_{ij}F_{kl}$). The correspondence is dimension-filtered, not a naive bijection.` },
  { id: 'YM-11', title: 'Short-distance identity', cls: 'NORMATIVE', anchor: r`S1 \S4`, interp: ['I-4'],
    text: r`Correlation functions agree at short distances with asymptotic freedom and perturbative renormalization theory.` },
  { id: 'YM-12', title: 'Stress tensor and OPE', cls: 'NORMATIVE', anchor: r`S1 \S4`,
    text: r`Existence of a stress tensor and of an operator product expansion with the local singularities predicted by asymptotic freedom.` },
  { id: 'YM-13', title: 'Mass gap', cls: 'NORMATIVE', anchor: r`S1 \S4`,
    text: r`$\exists\,\Delta>0:\ \sigma(H)\cap(0,\Delta)=\varnothing$.` },
  { id: 'YM-14', title: 'Finite mass', cls: 'NORMATIVE', anchor: r`S1 \S4`,
    text: r`$m:=\sup\{\Delta\}<\infty$. Equivalently $H\neq 0$; with \ref{A-027} this excludes exactly $\mathcal H=\mathbb C\Omega$.` },
  { id: 'YM-15', title: 'Axiomatic strength', cls: 'NORMATIVE', anchor: r`S1 \S4`, interp: ['I-5'],
    text: r`Axiomatic properties at least as strong as S3 and S4. On the Euclidean route: the OS axioms in the corrected form of [OS75], including the linear growth condition (\ref{A-001}, \ref{A-002}).` },
  { id: 'YM-16', title: 'No weak existence', cls: 'NORMATIVE', anchor: r`S1 fn.~2`,
    text: r`Existence by compactness (subsequential limits) alone is excluded unless the axioms and the mass gap are established for the limit.` },
  { id: 'YM-17', title: 'UV regulator removed', cls: 'DERIVED', anchor: r`from YM-03`,
    text: r`Every UV regulator (lattice spacing $a$, momentum cut-off, \dots) is removed; the topology of convergence of the correlation functions is specified.` },
  { id: 'YM-18', title: 'IR regulator removed', cls: 'DERIVED', anchor: r`from YM-03`,
    text: r`Every IR regulator (volume $L$, boundary conditions) is removed; dependence on boundary conditions is absent or controlled.` },
  { id: 'YM-19', title: 'Properties survive limits', cls: 'DERIVED', anchor: r`from YM-05--16`,
    text: r`Reflection positivity, full Euclidean invariance $E(4)$ (restored from any lattice subgroup), locality, gauge invariance of observables and the gap bound hold for the \emph{limit}, not only along the approximation.` },
  { id: 'YM-20', title: 'Complete proof', cls: 'PROCEDURAL', anchor: r`S2 \S5(a)`,
    text: r`A complete mathematical solution: every step is proved, or reduced to a published theorem whose hypotheses are verified in the instance.` },
  { id: 'YM-21', title: 'Explicit correspondence', cls: 'PROCEDURAL', anchor: r`S2 \S5(d)`,
    text: r`The paper addresses the specific questions of the official description; a closely related question does not qualify.` },
  { id: 'YM-22', title: 'Self-containment', cls: 'PROCEDURAL', anchor: r`S2 \S6(d)`,
    text: r`CMI does not consider supplementary material submitted by the author: every essential step must be in the published work.` },
  { id: 'YM-23', title: 'Qualifying Outlet', cls: 'PROCEDURAL', anchor: r`S2 \S4(a), \S6`,
    text: r`Publication in a refereed mathematics publication of worldwide repute with named editorial board, qualified editors, a published refereeing process and MathSciNet listing. CMI keeps no list and gives no advice.` },
  { id: 'YM-24', title: 'Time and acceptance', cls: 'PROCEDURAL', anchor: r`S2 \S4(b)--(c), \S7`,
    text: r`At least two years since publication, survival of rigorous examination and general acceptance in the global mathematics community; only then may CMI decide on detailed consideration by a special advisory committee.` },
  { id: 'YM-25', title: 'Priority record', cls: 'GOVERNANCE', anchor: r`S2 \S8(b)`,
    text: r`CMI pays special attention to dependence on prior published insights: keep a contribution and priority ledger from day one.` },
];

export const interpretations = [
  { id: 'I-1', title: 'Non-triviality',
    issue: r`S1 requires a \enquote{non-trivial} theory but does not define the term.`,
    reading: r`$\mathcal T_G$ is not isomorphic to (i) the one-dimensional theory $\mathcal H=\mathbb C\Omega$ (already excluded by YM-14), (ii) the Wick-polynomial theory of $\dim\mathfrak g$ free massless vector fields (already excluded by YM-13, since it is gapless), or (iii) a generalized free (Gaussian) theory. Recommended certificate: prove YM-11 for at least one connected $n$-point function, $n\ge 3$, whose leading perturbative coefficient is non-zero.`,
    positive: r`The certificate settles YM-04 and part of YM-11 together.`,
    negative: r`A result of the form \enquote{only trivial theories exist} must exclude (iii) explicitly.` },
  { id: 'I-2', title: 'Compact simple gauge group',
    issue: r`As an abstract group $SU(N)$ is not simple (centre $\mathbb Z_N$). The physics usage is: compact connected Lie group with simple, non-abelian Lie algebra. Different global forms (e.g.\ $SU(N)$ and $SU(N)/\mathbb Z_N$) share the local operator content on $\mathbb R^4$ and differ in line operators and $\theta$-periodicity [AST13].`,
    reading: r`The quantifier ranges over all compact simple Lie algebras $\mathfrak g\in\{A_n(n\ge1),B_n(n\ge2),C_n(n\ge3),D_n(n\ge4),E_6,E_7,E_8,F_4,G_2\}$, each with any compact connected $G$ such that $\operatorname{Lie}(G)=\mathfrak g$.`,
    positive: r`A method that works only for $SU(3)$, or only for $SU(N)$, does not suffice: all four classical families and all five exceptional algebras are required.`,
    negative: r`A counterexample for one single $\mathfrak g$ suffices.` },
  { id: 'I-3', title: 'Theta parameter',
    issue: r`The Lagrangian (1) of S1 has no topological $\theta$-term, although the quantum theory admits one.`,
    reading: r`The target is the $\theta=0$ theory.`,
    positive: r`$\theta=0$ suffices (existential quantifier).`,
    negative: r`Unless CMI's reading restricts to $\theta=0$, a non-existence result would also have to cover $\theta\neq0$. Flag for expert confirmation.` },
  { id: 'I-4', title: 'Short-distance agreement',
    issue: r`\enquote{Agree at short distances with the predictions of asymptotic freedom and perturbative renormalization theory, as described in textbooks} does not specify which correlation functions or to which order.`,
    reading: r`For gauge-invariant local fields, Schwinger functions at non-coinciding points, scaled towards a point, have asymptotic expansions in the running coupling $\bar g(\mu)$ that match renormalized perturbation theory order by order. Minimal certificate: leading-logarithmic agreement including the universal coefficients $b_0,b_1$ (\ref{A-009}).`,
    positive: r`The order of agreement must be stated explicitly in the main theorem.`,
    negative: r`Ambiguity here is a candidate for S2 \S5(c)(ii) (reformulation), not for the Prize.` },
  { id: 'I-5', title: 'Axiom set',
    issue: r`\enquote{At least as strong as those cited in [45, 35]}: [45] gives the Wightman axioms, [35] is OS~I \emph{and} OS~II. The reconstruction claim of OS~I is false without the linear growth condition (\ref{A-002}).`,
    reading: r`Wightman axioms as in Definition~\ref{def:wightman}; on the Euclidean route the OS axioms including the linear growth condition of [OS75]. A Haag--Kastler net alone is not sufficient, because the requirement cites [45, 35], not [24].`,
    positive: r`Prove OS0$'$ (linear growth) explicitly; it is the axiom most often forgotten.`,
    negative: r`\enquote{The axioms are too restrictive} is an opinion, not a counterexample (Section~\ref{sec:negative}).` },
  { id: 'I-6', title: 'Form of publication',
    issue: r`S2 speaks of \enquote{the Proposed Solution} published in a Qualifying Outlet and does not say how a series of papers is treated.`,
    reading: r`A series of refereed papers is acceptable in principle, but one main paper must contain the complete logical chain (the \enquote{Clay corollary}) with exact references to the published components.`,
    positive: r`No essential step may live only in code, data or supplements (YM-22).`,
    negative: r`Same rule.` },
];

// type:   DEF | THM | PERT | HEUR | NUM | HYP | TOOL
// status: VERIFIED  – checked against the cited primary text in this revision
//         STANDARD  – standard result; exact theorem locator still to be pinned
//         PARTIAL   – proved in a restricted setting (scope says what is missing)
//         OPEN      – not known
//         FALSE     – false as stated / as an implication
//         HEURISTIC – may guide research, never support a proof step
//         NUMERICAL – numerical evidence only
//         PREPRINT  – not refereed
export const assumptions = [
  { id: 'A-001', type: 'THM', status: 'STANDARD', source: '[OS75]',
    text: r`OS reconstruction: Schwinger functions satisfying OS0$'$ (linear growth) and OS1--OS3 define a Wightman theory; cluster (OS4) $\Leftrightarrow$ uniqueness of the vacuum.`,
    scope: r`Exact theorem numbers to be pinned before use.` },
  { id: 'A-002', type: 'THM', status: 'FALSE', source: '[OS73], [OS75]',
    text: r`\enquote{OS axioms without the linear growth condition suffice for reconstruction} (claim of OS~I).`,
    scope: r`Proof error (Lemma 8.8 of OS~I); corrected in OS~II by adding the linear growth condition. Precedent: a foundational claim was falsified and repaired in print.` },
  { id: 'A-003', type: 'THM', status: 'VERIFIED', source: r`[OSe78]; S1 \S6.5`,
    text: r`The Wilson lattice gauge theory with compact $G$ is reflection positive.`,
    scope: r`Wilson action; lattice reflections.` },
  { id: 'A-004', type: 'THM', status: 'PARTIAL', source: '[OSe78], [Sei82], [SZZ23]',
    text: r`Lattice Yang--Mills at strong coupling (small $\beta$) has exponential clustering (a lattice mass gap) and an area law.`,
    scope: r`Only $\beta<\beta_0(G,d)$. The continuum limit requires $\beta\to\infty$ (weak coupling): the opposite regime.` },
  { id: 'A-005', type: 'THM', status: 'PARTIAL', source: '[Bal85]--[Bal89b], [Dim13a], [Dim13b]',
    text: r`Renormalization-group control of the 4D lattice gauge theory on a torus, uniformly in the lattice spacing (ultraviolet stability).`,
    scope: r`Fixed finite volume. Expectations of gauge-invariant observables and the continuum limit are not completed (S1 \S6.5).` },
  { id: 'A-006', type: 'THM', status: 'PARTIAL', source: '[MRS93]',
    text: r`Construction of YM$_4$ with an infrared cut-off in a continuum regularization.`,
    scope: r`IR cut-off remains; reflection positivity is not automatic for continuum regularizations (S1 \S6.5).` },
  { id: 'A-007', type: 'THM', status: 'FALSE', source: '[Gri78], [Sin78]',
    text: r`\enquote{A global continuous gauge-fixing section exists on the space of connections.}`,
    scope: r`Gribov ambiguity; Singer's theorem. Gauge fixing is only local or patchwise. A failing gauge-fixing method is not a counterexample to S1.` },
  { id: 'A-008', type: 'HEUR', status: 'HEURISTIC', source: 'textbooks',
    text: r`The formal path integral $Z^{-1}e^{-S_{\mathrm{YM}}(A)}\prod_x dA(x)$ is a measure.`,
    scope: r`No such measure is known; guidance only.` },
  { id: 'A-009', type: 'PERT', status: 'VERIFIED', source: '[GW73], [Pol73], [Cas74], [Jon74]',
    text: r`$\beta(g)=-b_0g^3-b_1g^5+O(g^7)$ with $b_0=\tfrac{11}{3}\tfrac{C_A}{16\pi^2}$, $b_1=\tfrac{34}{3}\tfrac{C_A^2}{(16\pi^2)^2}$, $C_A=h^\vee(\mathfrak g)>0$ for every simple $\mathfrak g$.`,
    scope: r`Perturbative statement. Its non-perturbative meaning must be proved (YM-11).` },
  { id: 'A-010', type: 'PERT', status: 'FALSE', source: r`S1 \S6.1`,
    text: r`\enquote{The perturbation series in $g$ converges.}`,
    scope: r`Divergent in most known examples; Borel methods of limited use.` },
  { id: 'A-011', type: 'NUM', status: 'NUMERICAL', source: '[MP99], [Chen06]',
    text: r`Lattice Monte Carlo: lightest $0^{++}$ glueball of $SU(3)$ at about $1.7$~GeV ($1730(50)(80)$ and $1710(50)(80)$ MeV).`,
    scope: r`Evidence, never proof. Use: sanity check for any claimed rigorous bound.` },
  { id: 'A-012', type: 'THM', status: 'FALSE', source: r`S1 \S5, \S6.5`,
    text: r`\enquote{$\Delta_{a,L}>0$ for all $(a,L)$ implies a positive gap in the limit.}`,
    scope: r`Non-uniform bounds may tend to $0$. A uniform bound in physical units is required (\ref{A-031}).` },
  { id: 'A-013', type: 'THM', status: 'FALSE', source: r`S1 fn.~2`,
    text: r`\enquote{A subsequential (compactness) limit settles existence.}`,
    scope: r`Explicitly excluded unless the axioms and the gap are proved for the limit (YM-16).` },
  { id: 'A-014', type: 'THM', status: 'VERIFIED', source: '[ADC21], [ADC24]',
    text: r`Scaling limits of critical 4D Ising and lattice $\phi^4$ models are Gaussian (marginal triviality).`,
    scope: r`Calibration: a rigorous 4D negative result concerns a specified class of approximations. The published proof itself received a corrigendum (2024).` },
  { id: 'A-015', type: 'THM', status: 'VERIFIED', source: r`[Aiz82], [Fro82]; S1 \S6.2`,
    text: r`Self-interacting single-component $\phi^4$ fields do not exist in $d\ge5$.`,
    scope: r`Calibration for the negative track. Yang--Mills differs: it is asymptotically free.` },
  { id: 'A-016', type: 'THM', status: 'STANDARD', source: '[GJ87], [SW64]',
    text: r`Under YM-05--YM-09 with a unique vacuum: gap of $H$ $\Leftrightarrow$ gap of $M=\sqrt{H^2-\vec P^2}$ on $\Omega^\perp$ $\Leftrightarrow$ uniform exponential decay in Euclidean time of truncated two-point functions of a vacuum-cyclic field family.`,
    scope: r`Locators to be pinned. Main tool for proving YM-13 from Euclidean data.` },
  { id: 'A-017', type: 'THM', status: 'VERIFIED', source: r`S1 \S5`,
    text: r`Gap $\Rightarrow$ clustering: for every $C<\Delta$ and every local $\mathcal O$ with $\langle\Omega,\mathcal O\Omega\rangle=0$, $|\langle\Omega,\mathcal O(\vec x)\mathcal O(\vec y)\Omega\rangle|\le e^{-C|\vec x-\vec y|}$ for large $|\vec x-\vec y|$.`,
    scope: r`Independent consistency check of any gap proof.` },
  { id: 'A-018', type: 'HYP', status: 'OPEN', source: '—',
    text: r`Full Euclidean invariance $E(4)$ is restored in the continuum limit of the Wilson lattice theory, whose symmetry is only hypercubic.`,
    scope: r`Critical and easy to overlook.` },
  { id: 'A-019', type: 'HYP', status: 'OPEN', source: r`S1 fn.~1`,
    text: r`Renormalized gauge-invariant composite fields (e.g.\ $\operatorname{Tr}F^2$) arise as limits of lattice observables, with finite additive and multiplicative renormalization and mixing only with fields of lower or equal dimension.`,
    scope: r`Needed for YM-10 to YM-12.` },
  { id: 'A-020', type: 'THM', status: 'STANDARD', source: '[OS73]',
    text: r`Reflection positivity is preserved under pointwise limits of Schwinger functionals on a fixed class of test functions.`,
    scope: r`Elementary (limits of positive semi-definite forms). The test-function classes along the approximation must match.` },
  { id: 'A-021', type: 'HYP', status: 'OPEN', source: '[OS75]',
    text: r`The linear growth condition OS0$'$ holds uniformly along the approximation and passes to the limit.`,
    scope: r`Needed for A-001.` },
  { id: 'A-022', type: 'HEUR', status: 'HEURISTIC', source: r`S1 \S1, \S5`,
    text: r`Confinement (area law for Wilson loops).`,
    scope: r`\emph{Not} required by S1 (listed as an extension). Must not be used as a premise unless proved.` },
  { id: 'A-023', type: 'THM', status: 'VERIFIED', source: '[GKS89], [Dri89], [Wit91], [Lev03]',
    text: r`Two-dimensional Yang--Mills on compact surfaces is constructed and exactly solvable.`,
    scope: r`No propagating gluons in 2D: a source of techniques, not evidence for the 4D gap.` },
  { id: 'A-024', type: 'THM', status: 'VERIFIED', source: r`[BFS79], [BBIJ84]; S1 \S6.4`,
    text: r`The 2D abelian Higgs model satisfies the OS axioms (BFS) and has a mass gap.`,
    scope: r`As of S1, the only complete interacting gauge theory satisfying the axioms.` },
  { id: 'A-025', type: 'HEUR', status: 'HEURISTIC', source: r`S1 \S6.6`,
    text: r`The gap may require a non-classical change of variables or duality transformation.`,
    scope: r`Research direction. Any duality used must itself be proved.` },
  { id: 'A-026', type: 'HEUR', status: 'HEURISTIC', source: r`[tH74]; S1 \S6.6`,
    text: r`Large-$N$ gauge/string duality for pure Yang--Mills.`,
    scope: r`S1: \enquote{no effective approach to the gauge theory without fermions}.` },
  { id: 'A-027', type: 'THM', status: 'STANDARD', source: '[SW64]',
    text: r`In a Wightman theory with a unique vacuum, every translation-invariant vector is a multiple of $\Omega$.`,
    scope: r`Locator to be pinned. Used in YM-14 and A-016.` },
  { id: 'A-028', type: 'DEF', status: 'VERIFIED', source: 'Cartan classification',
    text: r`Compact simple Lie algebras and dual Coxeter numbers: $h^\vee(A_n)=n+1$, $h^\vee(B_n)=2n-1$, $h^\vee(C_n)=n+1$, $h^\vee(D_n)=2n-2$, $h^\vee(E_6,E_7,E_8,F_4,G_2)=12,18,30,9,4$.`,
    scope: r`Normalization: long roots of length$^2=2$.` },
  { id: 'A-029', type: 'TOOL', status: 'PREPRINT', source: '[DHMN26]',
    text: r`Lean~4 formalization of the 4D free field satisfying the Glimm--Jaffe (OS-type) axioms.`,
    scope: r`Tooling precedent for Section~\ref{sec:verification}.` },
  { id: 'A-030', type: 'TOOL', status: 'PREPRINT', source: '[OSR26]',
    text: r`Public Lean~4 formalization of OS reconstruction (third-party repository).`,
    scope: r`Not independently reviewed here. Candidate infrastructure only.` },
  { id: 'A-031', type: 'HYP', status: 'OPEN', source: r`S1 \S5, \S6.5`,
    text: r`Uniform gap: $\exists\,c>0,\ a_0>0,\ L_0<\infty$ such that $\Delta_{a,L}\ge c\,\Lambda$ for all $0<a<a_0$, $L>L_0$ (physical units, $\Lambda$ a renormalized scale).`,
    scope: r`S1: \enquote{New ideas are needed}. The core open problem. Candidate decompositions: \ref{A-039} (Research Report 1), \ref{A-045} (Research Report 2); finite core \ref{A-047} (Research Report 3).` },
  { id: 'A-032', type: 'HYP', status: 'OPEN', source: '—',
    text: r`Non-triviality certificate of \ref{I-1}: a connected $n\ge3$ function of gauge-invariant fields matches its non-zero leading perturbative coefficient.`,
    scope: r`Needed for YM-04.` },
  { id: 'A-033', type: 'HYP', status: 'OPEN', source: '—',
    text: r`The construction is uniform in method across all compact simple $\mathfrak g$ (or is carried out algebra by algebra).`,
    scope: r`Needed for YM-02. Constants may depend on $\mathfrak g$.` },
  // Research Report 1 (2026-09-24): coupling window and reduction question.
  { id: 'A-034', type: 'HYP', status: 'OPEN', source: '[Bal87], [Dim13a]; Report 1',
    text: r`(R1) RG reduction: uniformly in $a$ and in the volume, block-spin RG maps the lattice theory to an effective unit-lattice theory at spacing $\ell_*$ with $\ell_*\Lambda\approx F(g_*)$ and action in a class $\mathcal A(g_*,\varepsilon)$, with control of gauge-invariant observables.`,
    scope: r`Extends \ref{A-005} to infinite volume and to the crossover scale. Ba{\l}aban's constants are not explicit.` },
  { id: 'A-035', type: 'HYP', status: 'OPEN', source: '[DS87], [SZ92], [MO94]; Report 1',
    text: r`(R2) Gauge-covariant finite-volume criterion: a mixing condition on one finite box for an effective gauge action implies exponential clustering of gauge-invariant local observables in infinite volume.`,
    scope: r`Classical for spin systems; not known for gauge theories.` },
  { id: 'A-036', type: 'HYP', status: 'OPEN', source: 'Report 1',
    text: r`(R3) The criterion of \ref{A-035} holds, with margin and certified (non-statistical) bounds, for every action in $\mathcal A(g_*,\varepsilon)$.`,
    scope: r`Dimensional barrier: about $4s^4$ links per box of side $s$, i.e.\ 3072 real dimensions for $s=4$ and $SU(2)$.` },
  { id: 'A-037', type: 'NUM', status: 'NUMERICAL', source: '[AT21]; Report 1',
    text: r`Coupling window for $SU(2)$, $d=4$, Wilson action: rigorous gap only at strong coupling, most explicit threshold $\beta<1/12$ (\ref{A-038}); scaling from $\beta\approx2.2$; between $\beta=2.30$ and $2.70$, $am_G$ falls by a factor 3.4 while $m_G/\sqrt\sigma$ stays within 3.3--3.8.`,
    scope: r`Evidence for \ref{A-031}, never proof.` },
  { id: 'A-038', type: 'THM', status: 'VERIFIED', source: '[SZZ23]',
    text: r`For $SU(N)$ and $|\beta_{\mathrm{SZZ}}|<1/(16(d-1))$, with action $N\beta_{\mathrm{SZZ}}\operatorname{Re}\sum_p\Tr Q_p$, the infinite-volume lattice measure is unique and has a strictly positive mass gap.`,
    scope: r`For $SU(2)$, $d=4$, Wilson normalisation: $\beta<1/12$ (conversion in Report 1). Strong coupling only; refines \ref{A-004}.` },
  { id: 'A-039', type: 'HYP', status: 'OPEN', source: 'Report 1',
    text: r`Reduction (Report 1, Proposal 3.1): \ref{A-034} $\wedge$ \ref{A-035} $\wedge$ \ref{A-036} $\Rightarrow$ \ref{A-031}.`,
    scope: r`The implication itself is unproved; open point: transfer of clustering from effective to original observables.` },
  { id: 'A-040', type: 'THM', status: 'PREPRINT', source: 'Report 1, Prop. 3.2',
    text: r`Limit of pointwise curvature methods: for $SU(N)$, $N$ even, the uniform Bakry--Émery condition $\mathrm{Ric}-\mathrm{Hess}\,S\ge K>0$ fails for $\beta_{\mathrm{SZZ}}\ge1/(8d)$ (pi-flux configuration). With \ref{A-038}, the optimal threshold of the method lies in $[1/(16(d-1)),1/(8d)]$; for $SU(2)$, $d=4$, Wilson normalisation: $\beta\in[1/12,1/8]$.`,
    scope: r`Own result with complete proof and numerical check; not refereed. Limits only uniform pointwise curvature arguments.` },
  // Research Report 2 (2026-09-25): direct attempt at the core via the multiscale Bakry–Émery route.
  { id: 'A-041', type: 'THM', status: 'VERIFIED', source: '[BBD24], Thm. 3.6',
    text: r`Multiscale Bakry--Émery criterion: for $\nu_0\propto e^{-V_0}P_C$ with $C=\int_0^\infty\dot C_t\,dt$, if $\dot C_t\,\mathrm{Hess}\,V_t\,\dot C_t-\frac12\ddot C_t\ge\dot\lambda_t\dot C_t$ for all $\varphi,t$ ($\dot\lambda_t$ may be negative), then a log-Sobolev inequality holds with $1/\gamma=\int_0^\infty e^{-2\lambda_t}dt$.`,
    scope: r`Stated for measures on a vector space with a Gaussian reference. Proved to cross non-convex regimes for sine-Gordon, near-critical Ising and $\phi^4_{2,3}$.` },
  { id: 'A-042', type: 'HYP', status: 'OPEN', source: 'Report 2',
    text: r`A gauge-covariant Polchinski-type flow for lattice Yang--Mills with a reference that is both globally defined and local, uniformly in $a$ and the volume, with control of large fields.`,
    scope: r`Gauge dilemma: maximal-tree gauges are global but their Gaussian variance grows with the volume; local covariant gauges are not global (\ref{A-007}).` },
  { id: 'A-043', type: 'HYP', status: 'OPEN', source: 'Report 2',
    text: r`Large-scale convexification: along such a flow the renormalized Yang--Mills potential satisfies the criterion of \ref{A-041} with a log-Sobolev constant of order $(a\Lambda)^{-2}$, uniformly in $a$ and the volume.`,
    scope: r`The mass-gap problem restated in multiscale form (dynamical mass generation as convexity).` },
  { id: 'A-044', type: 'HYP', status: 'OPEN', source: 'Report 2',
    text: r`Conversion of a (preconditioned) log-Sobolev or Poincaré inequality into exponential decay of gauge-invariant correlations at rate $\gtrsim a\Lambda$ in lattice units.`,
    scope: r`The generic finite-speed conversion gives a rate proportional to the dynamical gap and loses the square root (massive free field: gap $m^2$, decay rate $m$).` },
  { id: 'A-045', type: 'HYP', status: 'OPEN', source: 'Report 2',
    text: r`Multiscale route: \ref{A-042} $\wedge$ \ref{A-043} $\wedge$ \ref{A-044} $\Rightarrow$ \ref{A-031}.`,
    scope: r`The implication itself is only sketched.` },
  // Research Report 3 (2026-09-25): length of the bridge (Monte Carlo RG).
  { id: 'A-046', type: 'NUM', status: 'NUMERICAL', source: 'Report 3',
    text: r`Length of the bridge ($SU(2)$, $d=4$, Wilson projection): from $\beta=2.2$--$2.6$ the factor-2 RG flow reaches $\beta<1/12$ in 4--6 blocking steps.`,
    scope: r`Projection onto the Wilson action; blocking parameter $c=0.5$; final lattice $4^4$. Evidence only.` },
  { id: 'A-047', type: 'HYP', status: 'OPEN', source: 'Report 3',
    text: r`Finite core: a bounded number $k$ (independent of $a$) of RG steps at intermediate coupling, acting on a class $\mathcal A$ of effective actions, can be controlled with gauge-invariant observables and lands in the region of \ref{A-038}.`,
    scope: r`Together with \ref{A-034} this would reduce \ref{A-031} to a finite non-perturbative problem; faces the dimensional barrier of \ref{A-036}.` },
];

// A transition is a separate theorem on the path from the regularized model
// to the Clay statement. Premises must be admissible (no FALSE, HEURISTIC,
// NUMERICAL or PREPRINT entries). A transition is CLOSED only if every
// premise is VERIFIED or STANDARD.
export const transitions = [
  { id: 'T1', title: 'Regularized model', covers: ['YM-05'], premises: ['A-003'],
    text: r`Wilson measure $\mu_{a,L}$ on $G^{\text{links}}$: finite-dimensional, gauge invariant, reflection positive.` },
  { id: 'T2', title: r`UV limit $a\to0$ at fixed $L$`, covers: ['YM-17'], premises: ['A-005', 'A-019'],
    text: r`Existence of the continuum limit on $T^4$ for gauge-invariant observables.` },
  { id: 'T3', title: r`IR limit $L\to\infty$`, covers: ['YM-18', 'YM-03'], premises: ['A-031'],
    text: r`Infinite-volume limit on $\mathbb R^4$, driven by a volume-uniform gap or cluster bound.` },
  { id: 'T4', title: 'Symmetry restoration', covers: ['YM-19'], premises: ['A-018'],
    text: r`From hypercubic to full $E(4)$ invariance of the limiting Schwinger functions.` },
  { id: 'T5', title: r`Euclidean $\to$ Minkowski`, covers: ['YM-01', 'YM-05', 'YM-06', 'YM-07', 'YM-08', 'YM-09', 'YM-15'], premises: ['A-001', 'A-020', 'A-021'],
    text: r`OS reconstruction of a Wightman theory with unique vacuum.` },
  { id: 'T6', title: 'Field content and UV identity', covers: ['YM-10', 'YM-11', 'YM-12'], premises: ['A-009', 'A-019'],
    text: r`Renormalized local gauge-invariant fields, asymptotic freedom, stress tensor and OPE.` },
  { id: 'T7', title: 'Non-triviality', covers: ['YM-04'], premises: ['A-032'],
    text: r`The limit is not trivial or Gaussian (\ref{I-1}).` },
  { id: 'T8', title: 'Mass gap in the limit', covers: ['YM-13', 'YM-14', 'YM-16'], premises: ['A-016', 'A-027', 'A-031'],
    text: r`Positive spectral gap of the reconstructed $H$; clustering (\ref{A-017}) as an independent check.` },
  { id: 'T9', title: 'All gauge groups', covers: ['YM-02'], premises: ['A-028', 'A-033'],
    text: r`T1--T8 for every compact simple $\mathfrak g$.` },
];
