"""Evaluate the MCRG runs: RG step beta -> beta' and the length of the bridge.

Evidence class E4. Matching: an observable of the n-times blocked 16^4 lattice
at beta equals the same observable of the (n-1)-times blocked 8^4 lattice at
beta'. Both sides then live on a lattice of the same size (4^4 for n = 2,
8^4 for n = 1). Different observables and levels giving the same beta' is the
consistency check for projecting the blocked action onto the Wilson line.

    python mcrg_analyze.py
"""

import glob
import json
import math
import os

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, '..', 'reports', 'data')
BETA_RIGOROUS = 1 / 12     # SZZ23 in Wilson normalisation for SU(2), d = 4
BETA_METHOD_LIMIT = 1 / 8  # Report 1, Proposition 3.2


def load(L):
    runs = [json.load(open(p)) for p in glob.glob(os.path.join(HERE, 'runs', f'mcrg_L{L}_b*.json'))]
    return sorted(runs, key=lambda r: r['beta'])


def match(target, dtarget, grid_beta, grid_obs):
    """beta' with obs(beta') = target, by linear interpolation on a monotone grid."""
    order = np.argsort(grid_obs)
    xs, ys = np.array(grid_obs)[order], np.array(grid_beta)[order]
    if not xs[0] <= target <= xs[-1]:
        return float('nan'), float('nan')
    b = float(np.interp(target, xs, ys))
    lo = float(np.interp(max(target - dtarget, xs[0]), xs, ys))
    hi = float(np.interp(min(target + dtarget, xs[-1]), xs, ys))
    return b, abs(hi - lo) / 2


def main():
    big, small = load(16), load(8)
    if not big or not small:
        raise SystemExit('missing MCRG runs')
    sb = [r['beta'] for r in small]
    rows = []
    for r in big:
        est = {}
        for n in (1, 2):                      # blocking level on the 16^4 lattice
            for k, name in ((0, 'P'), (1, 'R')):
                target, dt = r['observables'][n][k], r['errors'][n][k]
                grid = [s['observables'][n - 1][k] for s in small]
                est[f'{name}{n}'] = match(target, dt, sb, grid)
        rows.append((r['beta'], est))

    print(f"{'beta':>5} " + ' '.join(f"{k:>16}" for k in ('P1', 'R1', 'P2', 'R2')))
    for b, est in rows:
        print(f"{b:5.2f} " + ' '.join(f"{est[k][0]:8.3f}({est[k][1]:.3f})" for k in ('P1', 'R1', 'P2', 'R2')))

    # Flow map from the most blocked plaquette matching (P2), falling back to P1.
    flow = []
    for b, est in rows:
        bp = est['P2'][0] if not math.isnan(est['P2'][0]) else est['P1'][0]
        flow.append((b, bp))
    fb = np.array([f[0] for f in flow])
    fp = np.array([f[1] for f in flow])

    def step(beta):
        if beta <= fb[0]:
            # below the smallest measured coupling, scale linearly towards 0 (conservative: the
            # strong-coupling flow is faster than linear, so this overestimates the step count)
            return beta * fp[0] / fb[0]
        return float(np.interp(beta, fb, fp))

    trajectories = []
    for start in (2.6, 2.4, 2.2):
        path = [start]
        while path[-1] >= BETA_RIGOROUS and len(path) < 20:
            path.append(step(path[-1]))
        trajectories.append(path)
        print(f"start {start}: " + ' -> '.join(f'{x:.3f}' for x in path))

    def steps_to(path, bound):
        return next(i for i, x in enumerate(path) if x < bound)

    os.makedirs(OUT, exist_ok=True)
    with open(os.path.join(OUT, 'mcrg_table.tex'), 'w') as f:
        f.write('% Generated by lab/mcrg_analyze.py. Do not edit by hand.\n')
        for b, est in rows:
            cells = []
            for k in ('P1', 'R1', 'P2', 'R2'):
                x, dx = est[k]
                cells.append('---' if math.isnan(x) else f'${x:.3f}({max(1, round(dx * 1000)):d})$')
            f.write(f"{b:.1f} & " + ' & '.join(cells) + f" & ${b - (est['P2'][0] if not math.isnan(est['P2'][0]) else est['P1'][0]):.3f}$\\\\\n")
        f.write('\\bottomrule\n')
    with open(os.path.join(OUT, 'mcrg_flow.tex'), 'w') as f:
        f.write('% Generated by lab/mcrg_analyze.py. Do not edit by hand.\n')
        for path in trajectories:
            f.write(' $\\to$ '.join(f'{x:.2f}' for x in path)
                    + f" & {steps_to(path, BETA_METHOD_LIMIT)} & {steps_to(path, BETA_RIGOROUS)}\\\\\n")
        f.write('\\bottomrule\n')
    with open(os.path.join(OUT, 'mcrg_constants.tex'), 'w') as f:
        f.write('% Generated by lab/mcrg_analyze.py. Do not edit by hand.\n')
        f.write(f"\\newcommand{{\\BridgeStepsMax}}{{{max(steps_to(p, BETA_RIGOROUS) for p in trajectories)}}}\n")
        f.write(f"\\newcommand{{\\BridgeStepsMin}}{{{min(steps_to(p, BETA_RIGOROUS) for p in trajectories)}}}\n")
        f.write(f"\\newcommand{{\\McrgC}}{{{big[0]['c']}}}\n")
        f.write(f"\\newcommand{{\\McrgMeasBig}}{{{big[0]['n_measurements']}}}\n")
        f.write(f"\\newcommand{{\\McrgMeasSmall}}{{{small[0]['n_measurements']}}}\n")
        f.write(f"\\newcommand{{\\McrgNumSmall}}{{{len(small)}}}\n")


if __name__ == '__main__':
    main()
